title: Sharath Chandra Vijayakumar
logo: image/Headshot.jpeg
show_downloads: true
theme: jekyll-theme-minimal
Connect : Feel free to reach out via [email](mailto:sharathcvijay@gmail.com) or connect with me on [LinkedIn](https://linkedin.com/in/sharathchandra-rv/)
