title: Sharath Chandra Vijayakumar
logo: image/Headshot.jpeg
show_downloads: true
theme: jekyll-theme-minimal

connect_email: "mailto:sharathcvijay@gmail.com"
connect_linkedin: "https://linkedin.com/in/sharathchandra-rv/"
